configfile: "config/config.yaml"

include: "rules/common.smk"

rule all:
    input:
        # MD5 checksums for FASTQ files
        expand("results/{sample}/reads/{sample}_{read}.fastq.gz.md5",
               sample=unit_table.index, read=["R1", "R2"]),
        "results/merged/fastp_stats.tsv",
        "results/merged/fastp_stats_q20_q30.tsv"

include: "rules/input.smk"
include: "rules/qc.smk"
